#include <SPGrid_Fluids/Grids/GRID_HIERARCHY_ITERATOR.cpp>
#include "ADAPTIVE_SUBDOMAIN_POISSON_DATA.h"
#include "BOUNDARY_REFINEMENT_RASTERIZER.h"
#include "../SPGrid_Domain_Decomposition_Solver/SPGRID_DOMAIN_DECOMPOSITION_DATA.h"

template class GRID_HIERARCHY_ITERATOR<2,BOUNDARY_REFINEMENT_RASTERIZER<ADAPTIVE_SUBDOMAIN_POISSON_DATA<float>,SPGRID_DOMAIN_DECOMPOSITION_DATA<float>,float,2> >;
template class GRID_HIERARCHY_ITERATOR<3,BOUNDARY_REFINEMENT_RASTERIZER<ADAPTIVE_SUBDOMAIN_POISSON_DATA<float>,SPGRID_DOMAIN_DECOMPOSITION_DATA<float>,float,3> >;
#ifndef COMPILE_WITHOUT_DOUBLE_SUPPORT
template class GRID_HIERARCHY_ITERATOR<2,BOUNDARY_REFINEMENT_RASTERIZER<ADAPTIVE_SUBDOMAIN_POISSON_DATA<double>,SPGRID_DOMAIN_DECOMPOSITION_DATA<double>,double,2> >;
template class GRID_HIERARCHY_ITERATOR<3,BOUNDARY_REFINEMENT_RASTERIZER<ADAPTIVE_SUBDOMAIN_POISSON_DATA<double>,SPGRID_DOMAIN_DECOMPOSITION_DATA<double>,double,3> >;
#endif
