#include <SPGrid_Fluids/Grids/GRID_HIERARCHY.cpp>

#include "ADAPTIVE_SUBDOMAIN_POISSON_DATA.h"

template class GRID_HIERARCHY<ADAPTIVE_SUBDOMAIN_POISSON_DATA<float>,float,2>;
template class GRID_HIERARCHY<ADAPTIVE_SUBDOMAIN_POISSON_DATA<float>,float,3>;
#ifndef COMPILE_WITHOUT_DOUBLE_SUPPORT
template class GRID_HIERARCHY<ADAPTIVE_SUBDOMAIN_POISSON_DATA<double>,double,2>;
template class GRID_HIERARCHY<ADAPTIVE_SUBDOMAIN_POISSON_DATA<double>,double,3>;
#endif
